services:
  web:
    depends_on:
      - postgres_db
    build: 
      context: ./web 
      dockerfile: Dockerfile
    image: django-k8s:v1
    environment:
      - PORT=8080
    env_file:
      - web/.env 
    ports:
      - "8000:8080"
    command: sh -c "chmod +x /app/migrate.sh  && sh /app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres 
    command: -p 5432
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    env_file:
      - web/.env       
  redis_db:
    image: redis
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
      - redis_data:/data 
    entrypoint: redis-server --appendonly yes --port 6388

volumes:
  postgres_data:
  redis_data: 
