apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-webapp-deployment
  labels:
    app: django-webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-webapp-deployment
  template:
    metadata:
      labels:
        app: django-webapp-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/prod-django-registry/django-k8s-web:v2 
        envFrom:
          - secretRef: 
              name: django-k8s-web-prod-env
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: prod-django-registry
---

apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
    type: LoadBalancer
    ports: 
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8000
    selector:
      app: django-webapp-deployment
