name: Build docker container and push to registry
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  test_django: 
    uses: yourfavengineer/django-webapp/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django]
    defaults:
      run:
        working-directory: ./web
    env:
      DJANGO_SECRET_KEY: my-django-secret-key 
    steps:
      - uses: actions/checkout@v2