name: Build docker container and push to registry
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  test_django: 
    uses: yourfavengineer/django-webapp/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django]
    defaults:
      run:
        working-directory: ./web
    env:
      DJANGO_SECRET_KEY: my-django-secret-key 
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install digital ocean CLI
      uses: digitalocean/action-doctl@v2 
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Login to Docker container registry
      run: doctl registry login --expiry-seconds 200
    - name: build docker container images 
      working-directory: ./web 
      run: | 
        docker build -f Dockerfile . \
          -t registry.digitalocean.com/cfe-k8s/django-k8s-web:latest \
          -t registry.digitalocean.com/cfe-k8s/django-k8s-web:${GITHUB_SHA::7}
    - name: push images 
      run: docker push registry.digitalocean.com/cfe-k8s/django-k8s-web --all-tags
